### ISSUE TITLE
 No such file or directory: '/content/MOENAS-TF-PSI/data/NASBench201/[ImageNet16-120]_data.p'

### ISSUE THREAD

**Issue by siedmohsen2** [ELO-Lab/MOENAS-TF-PSI#1]
Hi authors!
Thanks for sharing your code.
I want to run your code and get an Error
```Traceback (most recent call last):
  File "/content/MOENAS-TF-PSI/main.py", line 204, in <module>
    main(args)
  File "/content/MOENAS-TF-PSI/main.py", line 46, in main
    problem.set_up()
  File "/content/MOENAS-TF-PSI/problems/direct/NAS_problem.py", line 22, in set_up
    self._set_up()
  File "/content/MOENAS-TF-PSI/problems/direct/nasbench201.py", line 55, in _set_up
    f_data = open(f'{self.path_data}/[{self.dataset}]_data.p', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/content/MOENAS-TF-PSI/data/NASBench201/[ImageNet16-120]_data.p'```


In file "nasbench201.py" you open some pickle files, not in your code Or your Google drive! where are there? how could I generate them?
I'm so appreciative to help me.

Thank's a lot.

**Comment by f4nku4n** [comment]
Hi, 
Sorry for my mistake, I have re-upload the data in the link in README.md.
You can download the data now. Thanks for your comments.

Btw, please let me know if you meet another problem.

**Comment by f4nku4n** [comment]
Update:
Because after this project, we have modify the database and so, the code cannot run now.
I will try to fix and update the new code soon.
